### ISSUE TITLE
fails upload on linux 

### ISSUE THREAD

**Issue by bm16ton** [rogerclarkmelbourne/Arduino_nrf51822#2]
Just like in the documentation " \\.\<THE COM PORT OF YOU BLACK MAGIC PROBE GDB SERER> " needs to be replaces with /dev/ttyACM0 etc i edited platform.txt and removed the \\.\ which fixed the 1st error I was getting, now it sits after the "monitor swdp_scan" showing "1 nrf51822" but doesnt look like it goes anywhere after that but maybe it does i dunno  I never see "upload finished" in the bottom window. So i click "sketch" then "export compiled binary" and I see the exported binary is a .hex but platform.txt has "file {build.project_name}.elf" so is it supposed to be an .elf file? also uploading the binary following the commands in platform.txt the command "tbreak main" always fails and tells me to use "file" command. I successfully uploaded my sketch this way both your example beacon and bleperipheral librarys hid example. the beacon I caint see on any of my devices except once in a great great while but the HID I see but cannot pair, but I can connect using bluetoothctl  altho moving the joystick does nothing so not sure difference between connect and pair is. the only other question I have is I uploaded s130_nrf51_1.0.0_softdevice.hex is this still the correct version? I see a bootloader file in your Arduino_nrf51822 folder not sure if the softdevice files are considered bootloaders or not but the file size of your bootloader is different then either s130_nrf51_1.0.0_softdevice.hex or s130_nrf51_2.0.1_softdevice.hex should i upload your bootloader same as the s130? I originally used your other arduino/nrf51822 repo but it wouldnt compile with bleperipheral and this one does (after changing include ble.h to nrf_ble.h which I guess in newest/newer redbearlab releases will be named ble.h again) I hafta say THANK YOU!! for both stm32 arduino stuff and the nrf51822! you have made it possible for people who Forest Gump there way thru this stuff, to actually be able to do this stuff! I truely appreciate it and thank you!

**Comment by rogerclarkmelbourne** [comment]
@bm16ton 

For this repo you need to use the V1.0 SD S130 (Which is part of SDK 10)

The BMP comm port is supposed to be selectable using the Tools->port setting in the Arduino IDE.
This isn't ideal as if you want to look at the Serial output, in the Arduino IDE you need to change the port after you have uploaded.

I'd also recommend that perhaps you look at Sandeep Mistry's new nRF5 Arduino core. I have a fork of it here https://github.com/rogerclarkmelbourne/arduino-nRF5

It uses SoftDevice 2.0 (or 2.0.1) (S130), and in the longer term I will remove my older repo's as Sandeeps is newer and better.

However Sandeep only wants to support upload via OpenOCD which requires additional programs etc to be installed and more setup to get the BMP to work.

So I suspect I will need to maintain a fork of Sandeeps repo just to be able to easily use the BMP

**Comment by bm16ton** [comment]
You are awesome! so manually using gdb and bmp i uploaded the HID example from bleperipheral and i could see connect and pair! Unfortunately i had specified the wrong pins so i recompiled/exported with correct pins now i caint see the nrf51822 from any of my hosts. I think ill retry from scratch mass erase reload s130 and then the app. Selecting the port works fine now that i removed  \.\  but the upload from arduino freezes just after the monitor swdp_scan listings im sure i can figure that out/fix that in time. Im a 33year old high school drop out, who  just recently got into arduino mcu's etc. and most of everything i have done has come directly from your work! I use a rectangle generic stm32f103c8 and nrf51822 for pretty much everything (caint afford anything else!) but someday when I have a little spare cash I would love to donate? (correct term?) to your efforts, do you have a paypal or something setup for that? You have truly made alot of things possible for me with your work and I hafta say THANK YOU! Your awesome and your work is awesome, the community owes you alot.
