### ISSUE TITLE
how to merger hex file generate from arduino with softdevice

### ISSUE THREAD

**Issue by cheeta1** [rogerclarkmelbourne/Arduino_nrf51822#3]
hi there, i have been trying to create a single firmware file by combining application file generated from arduino and softdevice S130. i used mergehex.exe of  nordic semicounductor but it give error saying these files are in conflict. apparently the file which arduino create also starts from 0x00 and when mergehex try to add both these it find them in conflict.
kindly tell me how can i merge softdevice and arduino created hex file 

thanks

**Comment by rogerclarkmelbourne** [comment]
I don't merge

I flash the SD and it just stays in the nRF51822

I then only need to flash the application hex when I recompile

**Comment by cheeta1** [comment]
what commands you use to change the start address to 1c3fc?

**Comment by rogerclarkmelbourne** [comment]
The hex or elf file contains the address information. You normally don't need to specify the address. 

i.e normally the file command reads the hex or elf file and the load command flashes it

e.g.
in platform.txt it has

-ex "file {build.project_name}.elf" -ex "load"

https://github.com/rogerclarkmelbourne/Arduino_nrf51822/blob/master/RBL_nRF51822/platform.txt#L147
